---

- name: Setup bash & git config files
  copy: src={{ item }} dest={{ lookup('env', 'HOME') }}/ owner={{ lookup('env', 'USER') }} group={{ lookup('env', 'USER') }} mode=644
  with_items:
    - .aliases
    - .bashrc
    - .bash_profile
    - .gitconfig
  become: false
