---

- name: Update all packages
  dnf: name=* state=latest

- name: Install RPM fusion
  dnf: 
    name: "https://download1.rpmfusion.org/free/fedora/rpmfusion-free-release-29.noarch.rpm" 
    state: present   

- name: Add additional rpm repositories
  yum_repository:
    name: "{{ item.name|mandatory }}"
    description:  "{{ item.description|mandatory }}"
    baseurl:  "{{ item.baseurl|mandatory }}"
    enabled:  "{{ item.enabled|default('yes') }}"
    gpgcheck:  "{{ item.gpgcheck|default('yes') }}"
    gpgkey:  "{{ item.gpgkey }}"
  loop: "{{ rpm_repos }}"

- name: Install preferred tools
  dnf: 
    name: "{{ preferred_tools }}"
    state: latest   
