---

- name: Update all packages
  dnf: name=* state=latest

#- name: Install RPM fusion
#  dnf: 
#    name: "https://download1.rpmfusion.org/free/fedora/rpmfusion-free-release-29.noarch.rpm" 
#    state: present   

- name: Add additional rpm repositories
  yum_repository:
    name: "{{ item.name|mandatory }}"
    description:  "{{ item.description|mandatory }}"
    baseurl:  "{{ item.baseurl|mandatory }}"
    enabled:  "{{ item.enabled|default('yes') }}"
    gpgcheck:  "{{ item.gpgcheck|default('yes') }}"
    gpgkey:  "{{ item.gpgkey }}"
  loop: "{{ rpm_repos }}"

- name: Install system tools
  dnf: 
    name: "{{ system_tools }}"
    state: latest   

- name: Install programming tools
  dnf: 
    name: "{{ program_tools }}"
    state: latest   

- name: Extract unrar 
  unarchive: 
    src: rarlinux-x64-4.0.1.tar.gz
    dest: /opt/

- name: Install unrar to usr/bin
  file: 
    src: /opt/rar/unrar
    dest: /usr/bin/unrar
    state: link
