program_tools: 
  - vim
  - gedit
  - tmux
  - lsof
  - git
  - gcc
  - gcc-c++
  - make
  - jq
  - yq
  - gettext
  - openssl
  - openssl-devel
  - openldap-clients
  - meld # compare tools with UI
  - kubectl
  # - yamllint
  # - haolint
  # - shellcheck

system_tools:
  - wget
  - gzip
  - autojump
  - htop
  - telnet
  - gimp
  - evince
  - foliate # this is a epub reader
  - krb5-workstation
  - google-chrome-stable
  - microsoft-edge-dev
  # - vlc
  # - ntp
  # - rhythmbox
  - libreoffice-writer
  - libreoffice-calc
  - libreoffice-impress
  - libreoffice-langpack-zh-Hans
  - dnf-utils
  - gnome-terminal
  - gnome-terminal-nautilus
  - ibus-libzhuyin

rpm_repos:
  - name: vscode
    description: "Visual Studio Code"
    baseurl: https://packages.microsoft.com/yumrepos/vscode
    enabled: yes
    gpgcheck: yes
    gpgkey: https://packages.microsoft.com/keys/microsoft.asc
  - name: google-chrome
    description: "Google Chrome repo"
    baseurl: http://dl.google.com/linux/chrome/rpm/stable/x86_64
    enabled: yes
    gpgcheck: yes
    gpgkey: https://dl.google.com/linux/linux_signing_key.pub
  - name: ms-edge-dev
    description: "Visual Studio Code"
    baseurl: https://packages.microsoft.com/yumrepos/edge
    enabled: yes
    gpgcheck: yes
    gpgkey: https://packages.microsoft.com/keys/microsoft.asc
  - name: Kubernetes
    description: "Kubernetes official repo"
    baseurl: https://pkgs.k8s.io/core:/stable:/v1.35/rpm/
    enabled: yes
    gpgcheck: yes
    gpgkey: https://pkgs.k8s.io/core:/stable:/v1.35/rpm/repodata/repomd.xml.key
