---

- name: Disable Selinux
  selinux:
    state: disabled

- name: Extract unrar 
  unarchive: 
    src: rarlinux-x64-4.0.1.tar.gz
    dest: /opt/

- name: Install unrar to usr/bin
  file: 
    src: /opt/rar/unrar
    dest: /usr/bin/unrar
    state: link