javaversions:
  - 1.8.0
  - 11
  - 17

devtools:
  - code
  - go
  - nodejs   
  - rust
  - cargo
  - kcat

npmpkgs: 
  - typescript
  - ts-node
  - ng
  - "@angular/cli"

installed_dockers: 
  - docker
  - docker-common
  - container-selinux
  - docker-selinux
  - docker-engine