devtools:
  - openjdk-8-jdk
  - openjdk-8-source
  - openjdk-11-jdk
  - openjdk-11-source
  - golang
  - nodejs   
  - npm
  - com.visualstudio.code

npmpkgs: 
  - typescript
  - ts-node
  - ng
  - "@angular/cli"

installed_dockers: 
  - docker
  - docker-engine
  - docker.io
  - containerd
  - runc