devtools:
  - java-1.8.0-openjdk
  - java-1.8.0-openjdk-src
  - java-1.8.0-openjdk-devel
  - code
  - go
  - nodejs   

npmpkgs: 
  - typescript
  - ts-node
  - ng
  - "@angular/cli"

installed_dockers: 
  - docker
  - docker-common
  - container-selinux
  - docker-selinux
  - docker-engine