---

- name: Install dev tools
  apt:
    name: "{{ devtools }}"
    state: latest

- name: Install global npm packages
  npm: 
    name: "{{ item }}"
    global: yes
  loop: "{{ npmpkgs }}"

### docker installation start

- name: remove diro docker stuff if installed
  apt:
    name: "{{ installed_dockers }}"
    state: absent

- name: install prerequisites for docker-ce
  apt:
    name: 
      - curl
      - ca-certificates
      - gnupg
      - lsb-release
    state: latest

- name: prepare docker-ce gpgs folder
  file: 
    path: /etc/apt/keyrings
    state: directory

- name: get docker-ce gpgs keys
  apt_key:
    url: https://download.docker.com/linux/ubuntu/gpg
    keyring: /etc/apt/keyrings/docker.gpg
    state: present

- name: set up docker-ce repo
  shell: echo "deb [arch=$(dpkg --print-architecture) signed-by=/etc/apt/keyrings/docker.gpg] https://download.docker.com/linux/ubuntu $(lsb_release -cs) stable" | sudo tee /etc/apt/sources.list.d/docker.list > /dev/null

- name: install docker ce
  apt:
    name: 
      - docker-ce
      - docker-ce-cli 
      - containerd.io 
      # - docker-compose-plugin
    state: latest

- name: add myself to docker group
  user:
    name: "{{ lookup('env', 'USER')|default(default_user) }}"
    groups: docker
    append: yes

- name: enable docker service  
  systemd:
    name: docker
    enabled: yes
    masked: no

### docker installation end
