---

- name: Install dev tools
  dnf: name={{ item }} state=latest
  with_items:    
    - java-1.8.0-openjdk
    - java-1.8.0-openjdk-src
    - java-1.8.0-openjdk-devel
    - code
    - go
    - nodejs   
  become: true

- name: Install global npm packages
  npm: name={{ item }} global=yes
  with_items:
    - typescript
    - ts-node
    - ng
    - "@angular/cli"
  become: true


- name: remove diro docker stuff if installed
  dnf:
    name: "{{ item }}"
    state: absent
  with_items:
    - docker
    - docker-common
    - container-selinux
    - docker-selinux
    - docker-engine
  become: true

- name: install dnf-plugin-core
  dnf: 
    name: dnf-plugins-core
    state: latest
  become: true

- name: install docker ce repo      
  command: dnf config-manager --add-repo https://download.docker.com/linux/fedora/docker-ce.repo
  become: true

- name: install docker ce
  dnf:
    name: docker-ce
    state: latest
  become: true